# Generated by Django 4.2.30 on 2026-09-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
