# Generated by Django 4.2.30 on 2026-09-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_review_rating_review_user_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='client_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Оценка'),
        ),
    ]
