# Generated by Django 4.2.30 on 2026-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_vacancy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.CharField(blank=True, default='Возможно', max_length=100, verbose_name='Порекомендуете друзьям'),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('search', 'Поисковик'), ('social', 'Соцсети'), ('friend', 'Друзья'), ('ad', 'Реклама'), ('dealer', 'Дилер'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Как вы о нас узнали'),
        ),
    ]
